name 'puppet-windows_python'
version '0.0.1'
source 'https://github.com/openstack-hyper-v/puppet-windows_python.git'
author 'Peter Pouliot <peter@pouliot.net>'
license 'Apache 2.0'
summary 'Module for building python stack on Windows'
description 'puppet module for managing python on windows'
dependency 'joshcooper/powershell'
dependency 'basti1302/windows_path'
dependency 'puppetlabs/registry'
dependency 'openstack-hyper-v/windows_common'
dependency 'openstack-hyper-v/windows_7zip'
